{
  "hash": "828c81545910c28bfee95945524a9ad9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Visualizing and summarizing relationships\"\nformat: \n  revealjs:\n    auto-stretch: true\n---\n\n\n\n\n\n# Setup\n\n## Packages\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse) # for data wrangling and visualization\nlibrary(openintro) # for data\nlibrary(scales)    # for pretty axis labels\n```\n:::\n\n\n\n## Data: Houses in Duke Forest\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(duke_forest)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 98\nColumns: 13\n$ address    <chr> \"1 Learned Pl, Durham, NC 27705\", \"1616…\n$ price      <dbl> 1520000, 1030000, 420000, 680000, 42850…\n$ bed        <dbl> 3, 5, 2, 4, 4, 3, 5, 4, 4, 3, 4, 4, 3, …\n$ bath       <dbl> 4.0, 4.0, 3.0, 3.0, 3.0, 3.0, 5.0, 3.0,…\n$ area       <dbl> 6040, 4475, 1745, 2091, 1772, 1950, 390…\n$ type       <chr> \"Single Family\", \"Single Family\", \"Sing…\n$ year_built <dbl> 1972, 1969, 1959, 1961, 2020, 2014, 196…\n$ heating    <chr> \"Other, Gas\", \"Forced air, Gas\", \"Force…\n$ cooling    <fct> central, central, central, central, cen…\n$ parking    <chr> \"0 spaces\", \"Carport, Covered\", \"Garage…\n$ lot        <dbl> 0.97, 1.38, 0.51, 0.84, 0.16, 0.45, 0.9…\n$ hoa        <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ url        <chr> \"https://www.zillow.com/homedetails/1-L…\n```\n\n\n:::\n:::\n\n\n\n## Price vs. area {.nostretch}\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](3-3-2-visualize-summarize-relationships_files/figure-revealjs/unnamed-chunk-4-1.png){width=1152}\n:::\n:::\n\n\n\n# Relationship between two numerical variables\n\n## Scatterplot {.nostretch}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(duke_forest, aes(x = area, y = price)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](3-3-2-visualize-summarize-relationships_files/figure-revealjs/area-price-scatter-1.png){width=1152}\n:::\n:::\n\n\n\n## Correlation coefficient\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nduke_forest |>\n  summarize(r = cor(area, price))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n      r\n  <dbl>\n1 0.667\n```\n\n\n:::\n:::\n\n\n\n## Characteristics of a relationship\n\n*between two numerical variables*\n\n::: columns\n::: {.column width=\"30%\"}\n-   **Direction:** Positive\n\n-   **Strength:** Moderately strong\n\n-   **Form:** Linear\n:::\n\n::: {.column width=\"40%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](3-3-2-visualize-summarize-relationships_files/figure-revealjs/unnamed-chunk-7-1.png){width=480}\n:::\n:::\n\n\n:::\n:::\n\n# Relationship between a numerical and a categorical variable\n\n## Distribution of house prices\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(duke_forest, aes(x = price)) +\n  geom_histogram(binwidth = 100000)\n```\n\n::: {.cell-output-display}\n![](3-3-2-visualize-summarize-relationships_files/figure-revealjs/unnamed-chunk-8-1.png){width=576}\n:::\n:::\n\n\n\n## Filled histograms\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(duke_forest, aes(x = price, fill = cooling)) +\n  geom_histogram(binwidth = 100000)\n```\n\n::: {.cell-output-display}\n![](3-3-2-visualize-summarize-relationships_files/figure-revealjs/unnamed-chunk-9-1.png){width=576}\n:::\n:::\n\n\n  \n## Side-by-side box plots\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(duke_forest, aes(x = price, y = cooling)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](3-3-2-visualize-summarize-relationships_files/figure-revealjs/unnamed-chunk-10-1.png){width=576}\n:::\n:::\n\n\n\n## Filled density plots\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|3|5\"}\nggplot(\n  duke_forest, \n  aes(x = price, color = cooling, fill = cooling)\n  ) +\n  geom_density(alpha = 0.5)\n```\n\n::: {.cell-output-display}\n![](3-3-2-visualize-summarize-relationships_files/figure-revealjs/unnamed-chunk-11-1.png){width=576}\n:::\n:::\n\n\n\n## Violin plots\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(duke_forest, aes(x = price, y = cooling)) +\n  geom_violin()\n```\n\n::: {.cell-output-display}\n![](3-3-2-visualize-summarize-relationships_files/figure-revealjs/unnamed-chunk-12-1.png){width=576}\n:::\n:::\n\n\n\n## Grouped summaries\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|2|3\"}\nduke_forest |>\n  group_by(cooling) |>\n  summarize(median_price = median(price))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  cooling median_price\n  <fct>          <dbl>\n1 other         525000\n2 central       550000\n```\n\n\n:::\n:::\n\n\n\n## Multiple summary statistics\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|4-7\"}\nduke_forest |>\n  group_by(cooling) |>\n  summarize(\n    min_price = min(price),\n    median_price = median(price), \n    iqr_price = IQR(price),\n    max_price = max(price)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  cooling min_price median_price iqr_price max_price\n  <fct>       <dbl>        <dbl>     <dbl>     <dbl>\n1 other       95000       525000    156500   1020000\n2 central    265000       550000    221500   1520000\n```\n\n\n:::\n:::\n\n\n\n# Relationship between two categorical variables\n\n## Year built\n\n::: task\nCreate a new variable called `year_built_cat` that takes on the value `\"1970 or later\"` if the house is built in 1970 or later, and `\"1969 or earlier\"` otherwise.\n:::\n\n. . .\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|2,8|3-7|4|5|6|1\"}\nduke_forest <- duke_forest |>\n  mutate(\n    year_built_cat = if_else(\n      year_built >= 1970, \n      \"1970 or later\", \n      \"1969 or earlier\"\n    )\n   )\n```\n:::\n\n\n\n## Year built\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nduke_forest |>\n  select(contains(\"year_built\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 98 × 2\n   year_built year_built_cat \n        <dbl> <chr>          \n 1       1972 1970 or later  \n 2       1969 1969 or earlier\n 3       1959 1969 or earlier\n 4       1961 1969 or earlier\n 5       2020 1970 or later  \n 6       2014 1970 or later  \n 7       1968 1969 or earlier\n 8       1973 1970 or later  \n 9       1972 1970 or later  \n10       1964 1969 or earlier\n# ℹ 88 more rows\n```\n\n\n:::\n:::\n\n\n\n## Stacked bar plot -- frequencies\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(duke_forest, aes(x = year_built_cat, fill = cooling)) +\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](3-3-2-visualize-summarize-relationships_files/figure-revealjs/unnamed-chunk-17-1.png){width=576}\n:::\n:::\n\n\n\n## Stacked bar plot -- proportions\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"2\"}\nggplot(duke_forest, aes(x = year_built_cat, fill = cooling)) +\n  geom_bar(position = \"fill\")\n```\n\n::: {.cell-output-display}\n![](3-3-2-visualize-summarize-relationships_files/figure-revealjs/unnamed-chunk-18-1.png){width=576}\n:::\n:::\n\n\n\n## Frequencies\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nduke_forest |>\n  count(year_built_cat, cooling)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  year_built_cat  cooling     n\n  <chr>           <fct>   <int>\n1 1969 or earlier other      39\n2 1969 or earlier central    27\n3 1970 or later   other      14\n4 1970 or later   central    18\n```\n\n\n:::\n:::\n\n\n\n## Proportions\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nduke_forest |>\n  count(year_built_cat, cooling) |>\n  group_by(year_built_cat) |>\n  mutate(prop = n / sum(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n# Groups:   year_built_cat [2]\n  year_built_cat  cooling     n  prop\n  <chr>           <fct>   <int> <dbl>\n1 1969 or earlier other      39 0.591\n2 1969 or earlier central    27 0.409\n3 1970 or later   other      14 0.438\n4 1970 or later   central    18 0.562\n```\n\n\n:::\n:::\n\n\n\n# Relationships between many variables\n\n## Price vs. area and cooling - 1 {.smaller}\n\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code  code-line-numbers=\"|1,7|2|3-6|8\"}\nggplot(\n  duke_forest, \n  aes(\n    x = area, y = price, \n    color = cooling, shape = cooling\n    )\n  ) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](3-3-2-visualize-summarize-relationships_files/figure-revealjs/unnamed-chunk-21-1.png){width=576}\n:::\n:::\n\n\n\n## Price vs. area and cooling - 2 {.smaller}\n\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code  code-line-numbers=\"8\"}\nggplot(\n  duke_forest, \n  aes(\n    x = area, y = price, \n    color = cooling, shape = cooling\n    )\n  ) +\n  geom_point(alpha = 0.7, size = 4)\n```\n\n::: {.cell-output-display}\n![](3-3-2-visualize-summarize-relationships_files/figure-revealjs/unnamed-chunk-22-1.png){width=576}\n:::\n:::\n\n\n\n## Price vs. area and cooling - 3 {.smaller}\n\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code  code-line-numbers=\"9-16\"}\nggplot(\n  duke_forest, \n  aes(\n    x = area, y = price, \n    color = cooling, shape = cooling\n    )\n  ) +\n  geom_point(alpha = 0.7, size = 4) +\n  labs(\n    title = \"Houses in Duke Forest\",\n    subtitle = \"Durham, NC\",\n    color = \"Cooling\", shape = \"Cooling\",\n    x = \"Area (square feet)\",\n    y = \"Price (USD)\",\n    caption = \"Source: Zillow, November 2020\"\n  )\n```\n\n::: {.cell-output-display}\n![](3-3-2-visualize-summarize-relationships_files/figure-revealjs/unnamed-chunk-23-1.png){width=576}\n:::\n:::\n\n\n\n## Price vs. area and cooling - 4 {.smaller}\n\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code  code-line-numbers=\"9-11\"}\nggplot(\n  duke_forest, \n  aes(\n    x = area, y = price, \n    color = cooling, shape = cooling\n    )\n  ) +\n  geom_point(alpha = 0.7, size = 4) +\n  scale_color_manual(\n    values = c(\"central\" = \"darkblue\", \"other\" = \"lightsalmon3\")\n    ) +\n  labs(\n    title = \"Houses in Duke Forest\",\n    subtitle = \"Durham, NC\",\n    color = \"Cooling\", shape = \"Cooling\",\n    x = \"Area (square feet)\",\n    y = \"Price (USD)\",\n    caption = \"Source: Zillow, November 2020\"\n  )\n```\n\n::: {.cell-output-display}\n![](3-3-2-visualize-summarize-relationships_files/figure-revealjs/unnamed-chunk-24-1.png){width=576}\n:::\n:::\n\n\n\n## Price vs. area and cooling - 5 {.smaller}\n\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code  code-line-numbers=\"9\"}\nggplot(\n  duke_forest, \n  aes(\n    x = area, y = price, \n    color = cooling, shape = cooling\n    )\n  ) +\n  geom_point(alpha = 0.7, size = 4) +\n  scale_x_continuous(labels = label_number(big.mark = \",\")) +\n  scale_color_manual(\n    values = c(\"central\" = \"darkblue\", \"other\" = \"lightsalmon3\")\n    ) +\n  labs(\n    title = \"Houses in Duke Forest\",\n    subtitle = \"Durham, NC\",\n    color = \"Cooling\", shape = \"Cooling\",\n    x = \"Area (square feet)\",\n    y = \"Price (USD)\",\n    caption = \"Source: Zillow, November 2020\"\n  )\n```\n\n::: {.cell-output-display}\n![](3-3-2-visualize-summarize-relationships_files/figure-revealjs/unnamed-chunk-25-1.png){width=576}\n:::\n:::\n\n\n\n## Price vs. area and cooling - 6 {.smaller}\n\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code  code-line-numbers=\"10\"}\nggplot(\n  duke_forest, \n  aes(\n    x = area, y = price, \n    color = cooling, shape = cooling\n    )\n  ) +\n  geom_point(alpha = 0.7, size = 4) +\n  scale_x_continuous(labels = label_number(big.mark = \",\")) +\n  scale_y_continuous(labels = label_dollar()) +\n  scale_color_manual(\n    values = c(\"central\" = \"darkblue\", \"other\" = \"lightsalmon3\")\n    ) +\n  labs(\n    title = \"Houses in Duke Forest\",\n    subtitle = \"Durham, NC\",\n    color = \"Cooling\", shape = \"Cooling\",\n    x = \"Area (square feet)\",\n    y = \"Price (USD)\",\n    caption = \"Source: Zillow, November 2020\"\n  )\n```\n\n::: {.cell-output-display}\n![](3-3-2-visualize-summarize-relationships_files/figure-revealjs/unnamed-chunk-26-1.png){width=576}\n:::\n:::\n\n\n\n## Price vs. area and cooling - 7\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nduke_forest |>\n  group_by(cooling) |>\n  summarize(r = cor(price, area))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  cooling     r\n  <fct>   <dbl>\n1 other   0.459\n2 central 0.854\n```\n\n\n:::\n:::\n\n\n\n## Price vs. area and cooling - 8  {.smaller}\n\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code  code-line-numbers=\"22\"}\nggplot(\n  duke_forest, \n  aes(\n    x = area, y = price, \n    color = cooling, shape = cooling\n    )\n  ) +\n  geom_point(alpha = 0.7, size = 4) +\n  scale_x_continuous(labels = label_number(big.mark = \",\")) +\n  scale_y_continuous(labels = label_dollar()) +\n  scale_color_manual(\n    values = c(\"central\" = \"darkblue\", \"other\" = \"lightsalmon3\")\n    ) +\n  labs(\n    title = \"Houses in Duke Forest\",\n    subtitle = \"Durham, NC\",\n    color = \"Cooling\", shape = \"Cooling\",\n    x = \"Area (square feet)\",\n    y = \"Price (USD)\",\n    caption = \"Source: Zillow, November 2020\"\n  ) +\n  facet_wrap(~cooling, ncol = 1)\n```\n\n::: {.cell-output-display}\n![](3-3-2-visualize-summarize-relationships_files/figure-revealjs/unnamed-chunk-28-1.png){width=576}\n:::\n:::\n\n\n\n## Price vs. area and cooling - 9 {.smaller}\n\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code  code-line-numbers=\"8,15\"}\nggplot(\n  duke_forest, \n  aes(\n    x = area, y = price, \n    color = cooling, shape = cooling\n    )\n  ) +\n  geom_point(alpha = 0.7, size = 4, show.legend = FALSE) +\n  scale_x_continuous(labels = label_number(big.mark = \",\")) +\n  scale_y_continuous(labels = label_dollar()) +\n  scale_color_manual(\n    values = c(\"central\" = \"darkblue\", \"other\" = \"lightsalmon3\")\n    ) +\n  labs(\n    title = \"Houses in Duke Forest, by cooling type\",\n    subtitle = \"Durham, NC\",\n    color = \"Cooling\", shape = \"Cooling\",\n    x = \"Area (square feet)\",\n    y = \"Price (USD)\",\n    caption = \"Source: Zillow, November 2020\"\n  ) +\n  facet_wrap(~cooling, ncol = 1)\n```\n\n::: {.cell-output-display}\n![](3-3-2-visualize-summarize-relationships_files/figure-revealjs/multivar-plot-1.png){width=576}\n:::\n:::\n\n\n\n## Price vs. area and cooling {.smaller}\n\n\n::: columns\n::: {.column width=\"30%\"}\n::: incremental\n- The relationship between area and price of homes in Duke Forest is positive and relatively strong, regardless of cooling type.\n- The relationship appears to be stronger, with a larger correlation coefficient (0.854 vs. 0.459), for homes cooled with central air. \n- However the large difference in correlation coefficients for these two groups might be due to the three potential outliers in the other group with high areas and low price.\n:::\n:::\n::: {.column width=\"40%\"}\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](3-3-2-visualize-summarize-relationships_files/figure-revealjs/unnamed-chunk-30-1.png){width=576}\n:::\n:::\n\n\n:::\n:::\n",
    "supporting": [
      "3-3-2-visualize-summarize-relationships_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}